### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by acorbin3**

### CODE REVIEW

**Comment by acorbin3** [comment]
Initial cut of Pull Request master template

**Review by jlsilvey — COMMENTED** [review]
It would be nice if we could configure the request to have only the checklists that are applicable to the item(s) under review.
Also dont think the independence note is necessary. PRB/CCB should assign the review task to someone who is independent.... that way theres no question about it.

**Comment by acorbin3** [comment]
> It would be nice if we could configure the request to have only the checklists that are applicable to the item(s) under review.
> Also dont think the independence note is necessary. PRB/CCB should assign the review task to someone who is independent.... that way theres no question about it.

For checklists we can create many templates such has Requirements_Review, Design_Review, which would just be a subset of this large one. Now if we are talking about when creating a pull request check the sections apply I dont think thats possible. So either 1 or all. Suggestion could be to delete the sections that are not required for the review?

- [x] Update to remove the independence note

**Review by jlsilvey — COMMENTED** [review]
How is the pull request being populated from the template? Are you copy/paste -ing the text into the pull request? or is there a way to pick the template you want when you create the pull request and have it auto populate the form?

**Comment by acorbin3** [comment]
> How is the pull request being populated from the template? Are you copy/paste -ing the text into the pull request? or is there a way to pick the template you want when you create the pull request and have it auto populate the form?

Yep, this merge is the template, once it gets merged then we can have the ability to chose this for the TDR pull request

**Comment by acorbin3** [comment]
@jlsilvey can this be approved?

**Review by jlsilvey — APPROVED** [review]

**Pull request merged**
