### PR TITLE
Merging placeholder functions

### PR DESCRIPTION
**Pull request by acorbin3**
Adding the placeholder functions defined in the LLR's to address the informal review. Due to the large changes we will add in a pull request

In this pull request it can be recommending to add implementation

### CODE REVIEW

**Comment by acorbin3** [comment]
This is associated to #1

**Review by jlsilvey — CHANGES_REQUESTED** [review]
add more code

**Review by acorbin3 — COMMENTED** [review]
Adding floor and square_root implementations

**Comment by acorbin3** [comment]
> add more code

@jlsilvey - review changes please :)

**Review by jlsilvey — APPROVED** [review]

**Pull request merged**
